### ISSUE TITLE
WdBrowser - Unexpected error on items with many instances

### ISSUE THREAD

**Issue by tholzheim** [WolfgangFahl/pyOnlineSpreadSheetEditing#36]
When searching for `Q13442814` the following error occurs
```bash
'WikiDataBrowser' object has no attribute 'propertySelection'

Traceback (most recent call last):
  File "wd/wdbrowser.py", line 670, in selectItem
    await self.trulyTabularAnalysis(self.tt)
  File "wd/wdbrowser.py", line 480, in trulyTabularAnalysis
    if self.propertySelection is None:
AttributeError: 'WikiDataBrowser' object has no attribute 'propertySelection'
```

**Comment by tholzheim** [comment]
The issue emerges from this section:
https://github.com/WolfgangFahl/pyOnlineSpreadSheetEditing/blob/e265a6358cb29c1d2a038a2dfabd5086e0ad424f/wd/wdbrowser.py#L667-L672

The methods have all their own exception handling and also define properties for the following methods to use.
Thus, side effects occur of the case that expected properties are not defined.
```python
await self.getCountQuery(self.tt),  #defines: ttcount
await self.getMostFrequentlyUsedProperties(self.tt),  #uses: ttcount | defines: ttquery,propertyQueryDisplay
await self.getPropertiesTable(self.tt, self.ttquery), #uses: ttquery  | defines: propertyList, propertySelection, ttTable
await self.trulyTabularAnalysis(self.tt) #uses: propertySelection
```
Resolved these side effects by removing the global exception handling within the methods and instead use more specific Exception handling such as: 
```python
try:
    self.propertyList=tt.sparql.queryAsListOfDicts(ttquery.query)
except EndPointInternalError as ex:
    if self.isTimeoutException(ex):
        raise Exception("Query timeout of the property table query")
```

**Comment by tholzheim** [comment]
With these fixes for the search `Q13442814` we now get:
* with wikidata:  `Query timeout of the property table query`
* with qlever: `QueryBadFormed [...] Tried to allocate 14029MB, but only 11362MB  were available. Clear the cache or allow more memory for QLever during startup`

>Thus, the Exception for items with many instances is not resolved but now the error messages indicate that the issue depends on the endpoints

**Comment by tholzheim** [comment]
The dependency and and possible side effects still need further investigation
e.g.
https://github.com/WolfgangFahl/pyOnlineSpreadSheetEditing/blob/8a19ba34c24cbeef7dcd04bfd07c46a0406244a8/wd/wdbrowser.py#L633-L637

**Comment by WolfgangFahl** [comment]
this might be a motivation to work on our own endpoint especially since the Wikidata Workshop paper has been accepted.
